name: pr_gatekepper
on : 
  pull_request:
    branches : 
    - main
  workflow_dispatch:

jobs :
  checks:
    runs-on: ubuntu-latest
    steps:
    - name : show targeting branch 
      run : echo" This Pull request is targetting the ${{ github.base_ref }}"
      
    - name: Show Pull request number 
      run: echo "This is pull Number ${{ github.event.pull_request.number}}"
    - name : Complete checks 
      run: "GAterkepper run complete"