name: The Python Inspector
 
on : 
  
    workflow_dispatch:
    
jobs:
    inspect:
        runs-on: ubuntu-latest 
        steps:
            - name : Checkout repository
              uses : actions/checkout@v7
            - name : Set up Python
              uses: actions/setup-python@v7
              with:
                python-version: '3.12'
            
            - name : print python version
              run : python --version
            - name : print pip version
              run : pip --version
            - name:  python binary location
              run : which python
            - name : print inspection complete
              run : echo "Python inspection complete"
            
            

        

